Setup ssh keys

diff --git a/setup.d/10_copy_ssh_keys b/setup.d/10_copy_ssh_keys
--- a/setup.d/10_copy_ssh_keys
+++ b/setup.d/10_copy_ssh_keys
@@ -1,11 +1,21 @@
 #! /bin/sh
 
+# Fail script if any command fails
+set -e
+
+## keep track of the last executed command
+trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
+## echo an error message before exiting
+trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT
+
 echo "Need to copy .ssh directory over from existing machine"
-echo "After copying the directory, and not before"
 echo
+echo "After copying the directory, and not before..."
+
 echo "Press any key to continue"
 while [ true ] ; do
-read -t 3 -n 1
+# read -t 3 -n 1
+read -n 1
 if [ $? = 0 ] ; then
 exit ;
 else
